name: Docker Build

on:
  push:
    branches:
      - main  # 设置触发条件，比如在 main 分支推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - { arch: amd64, dockerfile: Dockerfile.amd64 }
          - { arch: arm64, dockerfile: Dockerfile.arm64 }
          - { arch: 386, dockerfile: Dockerfile.386 }
          - { arch: arm/v7, dockerfile: Dockerfile.arm32 }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64,386,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tfcenter/service:latest
          file: ${{ matrix.platform.dockerfile }}
          platforms: linux/${{ matrix.platform.arch }}

      - name: Logout from Docker Hub
        run: docker logout
