name: Docker Build

on:
  push:
    branches:
      - main  # 设置触发条件，比如在 main 分支推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,amd64,386,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push multi-architecture Docker images
        run: |
          docker buildx create --use
          docker buildx build --push \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7 \
            -t tfcenter/service:latest \
            -f Dockerfile.multi .

      - name: Logout from Docker Hub
        run: docker logout